# frozen_string_literal: true
source "https://rubygems.org"

ruby '2.4.0'

# gem "rails"
# gem 'httpie'
gem 'sinatra'
gem 'capybara'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'simplecov', require: false, group: :test
gem 'simplecov-console', require: false, group: :test
gem 'shotgun'
gem 'thin'
